version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: /4k8f4JkNzu6jKVBJM2cCktQqmh+xJz/pzfg3096hLxX2fdmLfADZHvSOgEr1n2L
after_test: 
    -cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" DataStructure.Tests\bin\Debug\DataStructures.DataStructure.Tests.dll" -output:coverage.xml
    -cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
